---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Eigen Compile times (GCC)

The following commit was tested with `g++ (GCC) 7.2.1 20170829`

```
commit 716839ea79291efe769ee56ebdd783b9d2b3d51f (HEAD -> master, origin/master, origin/branches/default, origin/HEAD)
Author: Rasmus Munk Larsen <rmlarsen@google.com>
Date:   Wed Jun 5 16:42:27 2019 -0700

    Make is_valid_index_type return false for float and double when EIGEN_HAS_TYPE_TRAITS is off.
```
The timings were generated with the following script.

```sh
# Clone Eigen
git clone https://github.com/eigenteam/eigen-git-mirror
mkdir build
cd build/

# Download the 'time-g++.sh' script - a drop in replacement
# for g++ which tracks compile times and memory usage.
wget https://raw.githubusercontent.com/bjornpiltz/compiler_profiler/master/time-g%2B%2B.sh
chmod a+x time-g++.sh

# Configuration:
# Tell CMake to use time-g++.sh as a compiler
export CXX=$(pwd)/time-g++.sh

# Tell time-g++.sh which compiler to actually use
export ACTUAL_COMPILER=/usr/bin/g++

# Note to Mac users: The built-in time tool is unusable. 
# You have to install gtime with homebrew or MacPorts.
export TIME_CMD=/usr/bin/time

# Where do you want the output?
export PROFILING_LOG=$(pwd)/eigen_compile_times_gcc.csv

# Configure the Eigen test suite
cmake ../eigen-git-mirror/

# Clear the log after calling cmake to remove some noise.
rm $PROFILING_LOG

# Now compile the test suite and wait some seven hours...
make check
```

The following R code converts `eigen_compile_times_gcc.csv` to an html table.

```{r, message=FALSE, warning=FALSE, output=FALSE}
library(knitr)
library(kableExtra)
df = read.csv("eigen_compile_times_gcc.csv")

# sort by time:
df <- df[order(-df$Time..s.),]

kable(df) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

